import { Grade, Subject } from "@/types";

// Beyond K-12 — NiiDo caters to learners of any age, so both the real-account
// forms (signup/admin/teacher) and the assessment offer these same levels.
const HIGHER_ED: { value: Grade; label: string }[] = [
  { value: "undergrad_1",   label: "Undergraduate, Year 1" },
  { value: "undergrad_2",   label: "Undergraduate, Year 2" },
  { value: "undergrad_3",   label: "Undergraduate, Year 3" },
  { value: "undergrad_4",   label: "Undergraduate, Year 4" },
  { value: "undergrad_5",   label: "Undergraduate, Year 5+" },
  { value: "grad_masters",  label: "Graduate School, Master's" },
  { value: "grad_phd",      label: "Graduate School, PhD" },
];

// One label set used everywhere in the app (signup, complete-profile, admin,
// teacher tools, assessment) — the generic international "Grade N" numbering,
// not the Nigerian NERDC names (Primary/JSS/SSS). NiiDo positions itself as a
// global platform, not Nigeria-only, so the same grade should read the same
// way no matter which part of the app a user is in. The internal `value`
// slugs (primary_1, jss_1, sss_1, ...) are unchanged — only the label shown
// to users changed — since curriculum-aware backend logic (EduPrompt lesson
// generation) still needs to know this is Nigeria's JSS/SSS system.
export const GRADES: { value: Grade; label: string }[] = [
  { value: "primary_1", label: "Grade 1" },
  { value: "primary_2", label: "Grade 2" },
  { value: "primary_3", label: "Grade 3" },
  { value: "primary_4", label: "Grade 4" },
  { value: "primary_5", label: "Grade 5" },
  { value: "primary_6", label: "Grade 6" },
  { value: "jss_1",     label: "Grade 7" },
  { value: "jss_2",     label: "Grade 8" },
  { value: "jss_3",     label: "Grade 9" },
  { value: "sss_1",     label: "Grade 10" },
  { value: "sss_2",     label: "Grade 11" },
  { value: "sss_3",     label: "Grade 12" },
  ...HIGHER_ED,
];

// Nigeria first (launch market), then other African markets, then a spread of
// major global markets — NiiDo is positioned as global-first, Africa-launch.
// Flags are rendered via the flag-icons package (keyed off `iso`), not emoji —
// flag emoji don't render reliably on Windows.
export const COUNTRIES: { iso: string; name: string; dialCode: string }[] = [
  { iso: "NG", name: "Nigeria",        dialCode: "+234" },
  { iso: "GH", name: "Ghana",          dialCode: "+233" },
  { iso: "KE", name: "Kenya",          dialCode: "+254" },
  { iso: "ZA", name: "South Africa",   dialCode: "+27"  },
  { iso: "EG", name: "Egypt",          dialCode: "+20"  },
  { iso: "ET", name: "Ethiopia",       dialCode: "+251" },
  { iso: "TZ", name: "Tanzania",       dialCode: "+255" },
  { iso: "UG", name: "Uganda",         dialCode: "+256" },
  { iso: "RW", name: "Rwanda",         dialCode: "+250" },
  { iso: "SN", name: "Senegal",        dialCode: "+221" },
  { iso: "CI", name: "Côte d'Ivoire",  dialCode: "+225" },
  { iso: "CM", name: "Cameroon",       dialCode: "+237" },
  { iso: "US", name: "United States",  dialCode: "+1"   },
  { iso: "GB", name: "United Kingdom", dialCode: "+44"  },
  { iso: "CA", name: "Canada",         dialCode: "+1"   },
  { iso: "IN", name: "India",          dialCode: "+91"  },
  { iso: "PK", name: "Pakistan",       dialCode: "+92"  },
  { iso: "BD", name: "Bangladesh",     dialCode: "+880" },
  { iso: "PH", name: "Philippines",    dialCode: "+63"  },
  { iso: "BR", name: "Brazil",         dialCode: "+55"  },
  { iso: "AE", name: "UAE",            dialCode: "+971" },
  { iso: "FR", name: "France",         dialCode: "+33"  },
  { iso: "DE", name: "Germany",        dialCode: "+49"  },
  // Rest of the world, alphabetical — generated from libphonenumber-js's metadata
  // so every country phone auth can plausibly be used from is covered.
  { iso: "AF", name: "Afghanistan", dialCode: "+93" },
  { iso: "AX", name: "Åland Islands", dialCode: "+358" },
  { iso: "AL", name: "Albania", dialCode: "+355" },
  { iso: "DZ", name: "Algeria", dialCode: "+213" },
  { iso: "AS", name: "American Samoa", dialCode: "+1" },
  { iso: "AD", name: "Andorra", dialCode: "+376" },
  { iso: "AO", name: "Angola", dialCode: "+244" },
  { iso: "AI", name: "Anguilla", dialCode: "+1" },
  { iso: "AG", name: "Antigua & Barbuda", dialCode: "+1" },
  { iso: "AR", name: "Argentina", dialCode: "+54" },
  { iso: "AM", name: "Armenia", dialCode: "+374" },
  { iso: "AW", name: "Aruba", dialCode: "+297" },
  { iso: "AC", name: "Ascension Island", dialCode: "+247" },
  { iso: "AU", name: "Australia", dialCode: "+61" },
  { iso: "AT", name: "Austria", dialCode: "+43" },
  { iso: "AZ", name: "Azerbaijan", dialCode: "+994" },
  { iso: "BS", name: "Bahamas", dialCode: "+1" },
  { iso: "BH", name: "Bahrain", dialCode: "+973" },
  { iso: "BB", name: "Barbados", dialCode: "+1" },
  { iso: "BY", name: "Belarus", dialCode: "+375" },
  { iso: "BE", name: "Belgium", dialCode: "+32" },
  { iso: "BZ", name: "Belize", dialCode: "+501" },
  { iso: "BJ", name: "Benin", dialCode: "+229" },
  { iso: "BM", name: "Bermuda", dialCode: "+1" },
  { iso: "BT", name: "Bhutan", dialCode: "+975" },
  { iso: "BO", name: "Bolivia", dialCode: "+591" },
  { iso: "BA", name: "Bosnia & Herzegovina", dialCode: "+387" },
  { iso: "BW", name: "Botswana", dialCode: "+267" },
  { iso: "IO", name: "British Indian Ocean Territory", dialCode: "+246" },
  { iso: "VG", name: "British Virgin Islands", dialCode: "+1" },
  { iso: "BN", name: "Brunei", dialCode: "+673" },
  { iso: "BG", name: "Bulgaria", dialCode: "+359" },
  { iso: "BF", name: "Burkina Faso", dialCode: "+226" },
  { iso: "BI", name: "Burundi", dialCode: "+257" },
  { iso: "KH", name: "Cambodia", dialCode: "+855" },
  { iso: "CV", name: "Cape Verde", dialCode: "+238" },
  { iso: "BQ", name: "Caribbean Netherlands", dialCode: "+599" },
  { iso: "KY", name: "Cayman Islands", dialCode: "+1" },
  { iso: "CF", name: "Central African Republic", dialCode: "+236" },
  { iso: "TD", name: "Chad", dialCode: "+235" },
  { iso: "CL", name: "Chile", dialCode: "+56" },
  { iso: "CN", name: "China", dialCode: "+86" },
  { iso: "CX", name: "Christmas Island", dialCode: "+61" },
  { iso: "CC", name: "Cocos (Keeling) Islands", dialCode: "+61" },
  { iso: "CO", name: "Colombia", dialCode: "+57" },
  { iso: "KM", name: "Comoros", dialCode: "+269" },
  { iso: "CG", name: "Congo - Brazzaville", dialCode: "+242" },
  { iso: "CD", name: "Congo - Kinshasa", dialCode: "+243" },
  { iso: "CK", name: "Cook Islands", dialCode: "+682" },
  { iso: "CR", name: "Costa Rica", dialCode: "+506" },
  { iso: "HR", name: "Croatia", dialCode: "+385" },
  { iso: "CU", name: "Cuba", dialCode: "+53" },
  { iso: "CW", name: "Curaçao", dialCode: "+599" },
  { iso: "CY", name: "Cyprus", dialCode: "+357" },
  { iso: "CZ", name: "Czechia", dialCode: "+420" },
  { iso: "DK", name: "Denmark", dialCode: "+45" },
  { iso: "DJ", name: "Djibouti", dialCode: "+253" },
  { iso: "DM", name: "Dominica", dialCode: "+1" },
  { iso: "DO", name: "Dominican Republic", dialCode: "+1" },
  { iso: "EC", name: "Ecuador", dialCode: "+593" },
  { iso: "SV", name: "El Salvador", dialCode: "+503" },
  { iso: "GQ", name: "Equatorial Guinea", dialCode: "+240" },
  { iso: "ER", name: "Eritrea", dialCode: "+291" },
  { iso: "EE", name: "Estonia", dialCode: "+372" },
  { iso: "SZ", name: "Eswatini", dialCode: "+268" },
  { iso: "FK", name: "Falkland Islands", dialCode: "+500" },
  { iso: "FO", name: "Faroe Islands", dialCode: "+298" },
  { iso: "FJ", name: "Fiji", dialCode: "+679" },
  { iso: "FI", name: "Finland", dialCode: "+358" },
  { iso: "GF", name: "French Guiana", dialCode: "+594" },
  { iso: "PF", name: "French Polynesia", dialCode: "+689" },
  { iso: "GA", name: "Gabon", dialCode: "+241" },
  { iso: "GM", name: "Gambia", dialCode: "+220" },
  { iso: "GE", name: "Georgia", dialCode: "+995" },
  { iso: "GI", name: "Gibraltar", dialCode: "+350" },
  { iso: "GR", name: "Greece", dialCode: "+30" },
  { iso: "GL", name: "Greenland", dialCode: "+299" },
  { iso: "GD", name: "Grenada", dialCode: "+1" },
  { iso: "GP", name: "Guadeloupe", dialCode: "+590" },
  { iso: "GU", name: "Guam", dialCode: "+1" },
  { iso: "GT", name: "Guatemala", dialCode: "+502" },
  { iso: "GG", name: "Guernsey", dialCode: "+44" },
  { iso: "GN", name: "Guinea", dialCode: "+224" },
  { iso: "GW", name: "Guinea-Bissau", dialCode: "+245" },
  { iso: "GY", name: "Guyana", dialCode: "+592" },
  { iso: "HT", name: "Haiti", dialCode: "+509" },
  { iso: "HN", name: "Honduras", dialCode: "+504" },
  { iso: "HK", name: "Hong Kong SAR China", dialCode: "+852" },
  { iso: "HU", name: "Hungary", dialCode: "+36" },
  { iso: "IS", name: "Iceland", dialCode: "+354" },
  { iso: "ID", name: "Indonesia", dialCode: "+62" },
  { iso: "IR", name: "Iran", dialCode: "+98" },
  { iso: "IQ", name: "Iraq", dialCode: "+964" },
  { iso: "IE", name: "Ireland", dialCode: "+353" },
  { iso: "IM", name: "Isle of Man", dialCode: "+44" },
  { iso: "IL", name: "Israel", dialCode: "+972" },
  { iso: "IT", name: "Italy", dialCode: "+39" },
  { iso: "JM", name: "Jamaica", dialCode: "+1" },
  { iso: "JP", name: "Japan", dialCode: "+81" },
  { iso: "JE", name: "Jersey", dialCode: "+44" },
  { iso: "JO", name: "Jordan", dialCode: "+962" },
  { iso: "KZ", name: "Kazakhstan", dialCode: "+7" },
  { iso: "KI", name: "Kiribati", dialCode: "+686" },
  { iso: "XK", name: "Kosovo", dialCode: "+383" },
  { iso: "KW", name: "Kuwait", dialCode: "+965" },
  { iso: "KG", name: "Kyrgyzstan", dialCode: "+996" },
  { iso: "LA", name: "Laos", dialCode: "+856" },
  { iso: "LV", name: "Latvia", dialCode: "+371" },
  { iso: "LB", name: "Lebanon", dialCode: "+961" },
  { iso: "LS", name: "Lesotho", dialCode: "+266" },
  { iso: "LR", name: "Liberia", dialCode: "+231" },
  { iso: "LY", name: "Libya", dialCode: "+218" },
  { iso: "LI", name: "Liechtenstein", dialCode: "+423" },
  { iso: "LT", name: "Lithuania", dialCode: "+370" },
  { iso: "LU", name: "Luxembourg", dialCode: "+352" },
  { iso: "MO", name: "Macao SAR China", dialCode: "+853" },
  { iso: "MG", name: "Madagascar", dialCode: "+261" },
  { iso: "MW", name: "Malawi", dialCode: "+265" },
  { iso: "MY", name: "Malaysia", dialCode: "+60" },
  { iso: "MV", name: "Maldives", dialCode: "+960" },
  { iso: "ML", name: "Mali", dialCode: "+223" },
  { iso: "MT", name: "Malta", dialCode: "+356" },
  { iso: "MH", name: "Marshall Islands", dialCode: "+692" },
  { iso: "MQ", name: "Martinique", dialCode: "+596" },
  { iso: "MR", name: "Mauritania", dialCode: "+222" },
  { iso: "MU", name: "Mauritius", dialCode: "+230" },
  { iso: "YT", name: "Mayotte", dialCode: "+262" },
  { iso: "MX", name: "Mexico", dialCode: "+52" },
  { iso: "FM", name: "Micronesia", dialCode: "+691" },
  { iso: "MD", name: "Moldova", dialCode: "+373" },
  { iso: "MC", name: "Monaco", dialCode: "+377" },
  { iso: "MN", name: "Mongolia", dialCode: "+976" },
  { iso: "ME", name: "Montenegro", dialCode: "+382" },
  { iso: "MS", name: "Montserrat", dialCode: "+1" },
  { iso: "MA", name: "Morocco", dialCode: "+212" },
  { iso: "MZ", name: "Mozambique", dialCode: "+258" },
  { iso: "MM", name: "Myanmar (Burma)", dialCode: "+95" },
  { iso: "NA", name: "Namibia", dialCode: "+264" },
  { iso: "NR", name: "Nauru", dialCode: "+674" },
  { iso: "NP", name: "Nepal", dialCode: "+977" },
  { iso: "NL", name: "Netherlands", dialCode: "+31" },
  { iso: "NC", name: "New Caledonia", dialCode: "+687" },
  { iso: "NZ", name: "New Zealand", dialCode: "+64" },
  { iso: "NI", name: "Nicaragua", dialCode: "+505" },
  { iso: "NE", name: "Niger", dialCode: "+227" },
  { iso: "NU", name: "Niue", dialCode: "+683" },
  { iso: "NF", name: "Norfolk Island", dialCode: "+672" },
  { iso: "KP", name: "North Korea", dialCode: "+850" },
  { iso: "MK", name: "North Macedonia", dialCode: "+389" },
  { iso: "MP", name: "Northern Mariana Islands", dialCode: "+1" },
  { iso: "NO", name: "Norway", dialCode: "+47" },
  { iso: "OM", name: "Oman", dialCode: "+968" },
  { iso: "PW", name: "Palau", dialCode: "+680" },
  { iso: "PS", name: "Palestinian Territories", dialCode: "+970" },
  { iso: "PA", name: "Panama", dialCode: "+507" },
  { iso: "PG", name: "Papua New Guinea", dialCode: "+675" },
  { iso: "PY", name: "Paraguay", dialCode: "+595" },
  { iso: "PE", name: "Peru", dialCode: "+51" },
  { iso: "PL", name: "Poland", dialCode: "+48" },
  { iso: "PT", name: "Portugal", dialCode: "+351" },
  { iso: "PR", name: "Puerto Rico", dialCode: "+1" },
  { iso: "QA", name: "Qatar", dialCode: "+974" },
  { iso: "RE", name: "Réunion", dialCode: "+262" },
  { iso: "RO", name: "Romania", dialCode: "+40" },
  { iso: "RU", name: "Russia", dialCode: "+7" },
  { iso: "WS", name: "Samoa", dialCode: "+685" },
  { iso: "SM", name: "San Marino", dialCode: "+378" },
  { iso: "ST", name: "São Tomé & Príncipe", dialCode: "+239" },
  { iso: "SA", name: "Saudi Arabia", dialCode: "+966" },
  { iso: "RS", name: "Serbia", dialCode: "+381" },
  { iso: "SC", name: "Seychelles", dialCode: "+248" },
  { iso: "SL", name: "Sierra Leone", dialCode: "+232" },
  { iso: "SG", name: "Singapore", dialCode: "+65" },
  { iso: "SX", name: "Sint Maarten", dialCode: "+1" },
  { iso: "SK", name: "Slovakia", dialCode: "+421" },
  { iso: "SI", name: "Slovenia", dialCode: "+386" },
  { iso: "SB", name: "Solomon Islands", dialCode: "+677" },
  { iso: "SO", name: "Somalia", dialCode: "+252" },
  { iso: "KR", name: "South Korea", dialCode: "+82" },
  { iso: "SS", name: "South Sudan", dialCode: "+211" },
  { iso: "ES", name: "Spain", dialCode: "+34" },
  { iso: "LK", name: "Sri Lanka", dialCode: "+94" },
  { iso: "BL", name: "St. Barthélemy", dialCode: "+590" },
  { iso: "SH", name: "St. Helena", dialCode: "+290" },
  { iso: "KN", name: "St. Kitts & Nevis", dialCode: "+1" },
  { iso: "LC", name: "St. Lucia", dialCode: "+1" },
  { iso: "MF", name: "St. Martin", dialCode: "+590" },
  { iso: "PM", name: "St. Pierre & Miquelon", dialCode: "+508" },
  { iso: "VC", name: "St. Vincent & Grenadines", dialCode: "+1" },
  { iso: "SD", name: "Sudan", dialCode: "+249" },
  { iso: "SR", name: "Suriname", dialCode: "+597" },
  { iso: "SJ", name: "Svalbard & Jan Mayen", dialCode: "+47" },
  { iso: "SE", name: "Sweden", dialCode: "+46" },
  { iso: "CH", name: "Switzerland", dialCode: "+41" },
  { iso: "SY", name: "Syria", dialCode: "+963" },
  { iso: "TW", name: "Taiwan", dialCode: "+886" },
  { iso: "TJ", name: "Tajikistan", dialCode: "+992" },
  { iso: "TH", name: "Thailand", dialCode: "+66" },
  { iso: "TL", name: "Timor-Leste", dialCode: "+670" },
  { iso: "TG", name: "Togo", dialCode: "+228" },
  { iso: "TK", name: "Tokelau", dialCode: "+690" },
  { iso: "TO", name: "Tonga", dialCode: "+676" },
  { iso: "TT", name: "Trinidad & Tobago", dialCode: "+1" },
  { iso: "TA", name: "Tristan da Cunha", dialCode: "+290" },
  { iso: "TN", name: "Tunisia", dialCode: "+216" },
  { iso: "TR", name: "Türkiye", dialCode: "+90" },
  { iso: "TM", name: "Turkmenistan", dialCode: "+993" },
  { iso: "TC", name: "Turks & Caicos Islands", dialCode: "+1" },
  { iso: "TV", name: "Tuvalu", dialCode: "+688" },
  { iso: "VI", name: "U.S. Virgin Islands", dialCode: "+1" },
  { iso: "UA", name: "Ukraine", dialCode: "+380" },
  { iso: "UY", name: "Uruguay", dialCode: "+598" },
  { iso: "UZ", name: "Uzbekistan", dialCode: "+998" },
  { iso: "VU", name: "Vanuatu", dialCode: "+678" },
  { iso: "VA", name: "Vatican City", dialCode: "+39" },
  { iso: "VE", name: "Venezuela", dialCode: "+58" },
  { iso: "VN", name: "Vietnam", dialCode: "+84" },
  { iso: "WF", name: "Wallis & Futuna", dialCode: "+681" },
  { iso: "EH", name: "Western Sahara", dialCode: "+212" },
  { iso: "YE", name: "Yemen", dialCode: "+967" },
  { iso: "ZM", name: "Zambia", dialCode: "+260" },
  { iso: "ZW", name: "Zimbabwe", dialCode: "+263" },
];

export const SUBJECTS: { value: Subject; label: string }[] = [
  { value: "mathematics",         label: "Mathematics" },
  { value: "english",             label: "English" },
  { value: "basic_science",       label: "Basic Science" },
  { value: "social_studies",      label: "Social Studies" },
  { value: "civic_education",     label: "Civic Education" },
  { value: "agricultural_science", label: "Agricultural Science" },
  { value: "computer_studies",    label: "Computer Studies" },
  { value: "business_studies",    label: "Business Studies" },
  { value: "home_economics",      label: "Home Economics" },
  { value: "fine_art",            label: "Fine Art" },
  { value: "physical_education",  label: "Physical Education" },
];
